---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - custom_vars.yml
  
  roles:
    - role: ssh
      tags: ['ssh']
    - role: terminal
      tags: ['terminal']
    - role: productivity
      tags: ['productivity']
    - role: other
      tags: ['other']
    - role: web
      tags: ['web']
    - role: development
      tags: ['development']
    - role: macos
      tags: ['macos']