---
- name: Creating .ssh directory
  file:
    path: ~/.ssh/
    state: directory
    mode: 0700

- name: Copying password protected private ssh key
  copy:
    src: portovep
    dest: ~/.ssh/portovep
    mode: 0600

- name: Copying public ssh key
  copy:
    src: portovep.pub
    dest: ~/.ssh/portovep.pub
    mode: 0644

- name: Copying ssh config
  copy:
    src: ssh-config
    dest: ~/.ssh/config
    mode: 0600
