---
- name: Creating .ssh directory
  file:
    path: ~/.ssh/
    state: directory
    mode: 0700

- name: Copying password protected private ssh key
  copy:
    src: "{{ private_ssh_key_name }}"
    dest: ~/.ssh/{{ private_ssh_key_name }}
    mode: 0600

- name: Copying public ssh key
  copy:
    src: "{{ public_ssh_key_name }}"
    dest: ~/.ssh/{{ public_ssh_key_name }}
    mode: 0644

- name: Copying ssh config
  copy:
    src: ssh-config
    dest: ~/.ssh/config
    mode: 0600
