---
- name: Installing homebrew taps
  homebrew_tap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ homebrew_taps }}"

- name: Installing Cask packages
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    update_homebrew: yes
  with_items: "{{ cask_packages }}"

- name: Installing Homebrew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    update_homebrew: yes
  with_items: "{{ homebrew_packages }}"

- name: Installing global npm packages
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
  with_items: "{{ npm_packages }}"

- name: Installing global pip packages
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ pip_packages }}"
  become: yes

- name: Creating ~/Library/Application Support/Code/User directory
  file:
    path: ~/Library/Application Support/Code/User
    state: directory
    mode: 0700

- name: Copying VS Code settings to user's home
  copy:
    src: vscode-settings.json
    dest: ~/Library/Application Support/Code/User/settings.json
    mode: 0644

- name: Installing VS Code extensions
  shell: "code --install-extension {{ item }}"
  register: extension_result
  changed_when: "not extension_result.stdout|search('is already installed.')"
  with_items: "{{ vscode_extensions }}"

- name: Copying .gitconfig to user's home
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
    mode: 0644
